<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ChetnaM-PC" ignored="0" name="suite7" tests="5" failures="2" timestamp="26 May 2017 10:25:08 GMT" time="3048.358" errors="0">
  <testcase name="verify" time="800.009" classname="com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest.verify() didn&amp;apos;t finish within the time-out 800000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest.verify() didn't finish within the time-out 800000
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
  <testcase name="verify" time="228.748" classname="com.adv.qa.selenium.tests.currency.phase3.A107_Stores_HierarchyTest"/>
  <testcase name="verify" time="520.577" classname="com.adv.qa.selenium.tests.currency.phase3.A108_Item_Store_Controls_Manual_Store_HierarchyTest"/>
  <testcase name="verify" time="576.326" classname="com.adv.qa.selenium.tests.currency.phase3.A108A_Item_Store_Controls_Manual_Store_HierarchyTest"/>
  <testcase name="verify" time="800.015" classname="com.adv.qa.selenium.tests.currency.phase3.AD01004_Stock_Take_On_Using_Positive_AdjustmentTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.adv.qa.selenium.tests.currency.phase3.AD01004_Stock_Take_On_Using_Positive_AdjustmentTest.verify() didn&amp;apos;t finish within the time-out 800000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.adv.qa.selenium.tests.currency.phase3.AD01004_Stock_Take_On_Using_Positive_AdjustmentTest.verify() didn't finish within the time-out 800000
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.clickOnCancel(CurrencyPage.java:487)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.logOut(CurrencyPage.java:592)
	at com.adv.qa.selenium.tests.currency.phase3.AD01004_Stock_Take_On_Using_Positive_AdjustmentTest.verify(AD01004_Stock_Take_On_Using_Positive_AdjustmentTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- suite7 -->
