<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Draxayani-PC" name="suite" tests="2" failures="2" timestamp="30 Jun 2014 10:47:32 GMT" time="402.113" errors="0">
  <testcase name="verify" time="314.446" classname="com.adv.qa.selenium.tests.currency.phase2.A084_Authorisation_Value_Levels_DefinitionTest">
    <failure type="java.lang.AssertionError" message="New authorisation value levels  LEV1 not displayed in the list expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: New authorisation value levels  LEV1 not displayed in the list expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.adv.qa.selenium.framework.Assert.assertTrue(Assert.java:43)
	at com.adv.qa.selenium.tests.currency.phase2.A084_Authorisation_Value_Levels_DefinitionTest.createStructureAuthorisers(A084_Authorisation_Value_Levels_DefinitionTest.java:101)
	at com.adv.qa.selenium.tests.currency.phase2.A084_Authorisation_Value_Levels_DefinitionTest.verify(A084_Authorisation_Value_Levels_DefinitionTest.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
  <testcase name="verify" time="38.475" classname="com.adv.qa.selenium.tests.currency.phase2.A085_Authorisation_By_Value_LevelTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 5, Size: 5">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.adv.qa.selenium.framework.pageObjects.currency.CurrencyPage.enterValueLevelAuthForAP(CurrencyPage.java:4144)
	at com.adv.qa.selenium.tests.currency.phase2.A085_Authorisation_By_Value_LevelTest.createStructureAuthorisers(A085_Authorisation_By_Value_LevelTest.java:89)
	at com.adv.qa.selenium.tests.currency.phase2.A085_Authorisation_By_Value_LevelTest.verify(A085_Authorisation_By_Value_LevelTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- suite -->
