<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest" tests="1" time="800.009" ignored="0" failures="0" timestamp="26 May 2017 10:25:08 GMT" skipped="0" hostname="ChetnaM-PC" errors="1">
  <testcase name="verify" time="800.009" classname="com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest.verify() didn&#039;t finish within the time-out 800000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest.verify() didn't finish within the time-out 800000
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- verify -->
</testsuite> <!-- com.adv.qa.selenium.tests.currency.phase3.A106_Inventory_Store_ControlTest -->
